CQCL/portgraph

src/dot.rs
src/substitute.rs

Fixes a bug when merging edges in an empty graph in the `substitute` module.
It also fixes the clippy warnings

Fix bug in substitute

---

src/hierarchy.rs

Fixes a bug in `detach_children`, and adds `is_root`, `remove` and `shrink_to` methods.

Hierarchy fixes and docs

---

src/hierarchy.rs
src/secondary.rs
src/weights.rs

Adds tests and docs to `secondary_map`, `weights`, and `hierarchy`.
Changes:
- Adds `shrink_to` method
- Fixes UB in `get_disjoint_mut`. Thankfully miri caught it (the test was showing weird behaviour).
- Fix: `ensures_capacity` was a no-op.
- Adds `remove`, `is_root`, and `shrink_to` methods
- Fixes `detach_children` not updating part of the node info.

Fixes to the graph component modules

---

.github/workflows/ci.yml
src/portgraph.rs
src/secondary.rs
src/weights.rs

All these checks may get annoying at some point, but we can drop them later if needed.
CI runs in about 2mins so there's quick feedback for the errors.

Fix broken doc links, and add check to CI

---

src/dot.rs

Closes #17 
I've removed the `None` for edge style, as suggested in https://github.com/CQCL/portgraph/issues/17.
From the [dot docs](https://graphviz.org/docs/attr-types/style/), it seems the style should be in quotes, so I've also added that, made my change easier.

Change default dot edge style

---

src/lib.rs

I was getting confused by the off-by-one difference for the `Incoming(_)` variant.

Debug impl for PortOffset

---

.github/workflows/ci.yml

- Replaces [actions-rs/toolchain](http://github.com/actions-rs/toolchain) with [dtolnay/rust-toolchain](http://github.com/dtolnay/rust-toolchain), since the former is not being mantained and was throwing deprecation warnings.
- Splits the building and testing steps to differentiate when we an error occurs with `--no-default-features` vs `--all-features`.

Better names for the CI steps, update toolchain

---

.github/workflows/ci.yml

Move the "build benchmarks" step to its own CI job. This should cut CI times in half.

Split test and build bench CI job

---

src/hierarchy.rs
src/portgraph.rs

- Adds a `has_children` method to the hierarchy.
- Adds a Neighbours iterator to query the neighbour nodes directly.
- Adds an NodePortOffsets iterator, useful when using the methods introduced in #20

Add a couple helper methods

---

src/algorithms.rs
src/algorithms/dominators.rs
src/algorithms/post_order.rs
src/algorithms/toposort.rs

Similar to #30.
- Moves `algorithms/mod.rs` to `algorithms.rs`.
- Breaking change: Adds a `NodeIndex` parameter to the port filter in `toposort_filtered`, to avoid unnecessary calls to `portgraph::port_node` while filtering.

Add filtered versions of `dominators` and `postorder` algorithms

---

src/lib.rs
src/portgraph.rs
src/portgraph/iter.rs

Adds a port `capacity` field to `NodeMeta`. This lets us avoid reallocations when reducing the number of ports in a node.
- When reducing the total number of ports in a node, we can keep the allocated slab leaving empty spaces at the end.
- When increasing the number of ports over the capacity, we overallocate ports by rounding the slab size to the next power of two.
- On one hand, this reduces the number of allocations when adding ports repeatedly
- On the other hand, this makes more nodes share their slab sizes, increasing the hit-rate on the port slab free list.
- `add_node` does not overallocate. This avoids wasting space for nodes that never change their port count.
Closes #16 
<details>
<summary>Benchmark result vs HEAD (rounding up to powers of two)</summary>
```
graph …
```

Add port capacity to the nodes

---

src/secondary.rs

I think this would be a useful addition to `SecondaryMap`, covering most common use cases
of `rekey` callback functions.

Add rekey function

---

Cargo.toml
RELEASES.md

Includes a new method for rekeying secondary maps, and a fix for `set_num_ports`.

Release 0.2.3

---

src/portgraph.rs
src/portgraph/iter.rs

Adds a method to query the range from the node ports iterator.
Also fixes a couple minor doc errors.

Add `NodePorts::as_range`

---

src/algorithms/dominators.rs
src/algorithms/toposort.rs
src/hierarchy.rs
src/lib.rs
src/secondary.rs
src/unmanaged.rs
src/weights.rs

This is a big breaking change that will give us more flexibility when managing secondary data on a portgraph.
It adds a `SecondaryMap` trait that encapsulates the common interfaces we use when managing node and port data.
We can then implement that trait on different structures like the old `SecondaryMap` (now renamed `UnmanagedMap`), bit vec for boolean storage, and any {Hash,BTree}{Set,Map}. This closes #46.
With this, we can add a `Map` generic parameter to `DominatorTree` and `TopoSort` that lets us use more efficient structures when we do not traverse the full graph. This closes #31.
Also:
- Renames the old SecondaryMap struct as "UnmanagedMap".
- Implements SecondaryMap for BitVec.
- Uses the trait in Dominators and TopoSort to avoid wasting memory when doing partial traversals. …

Generic trait for SecondaryMaps

---

src/portgraph.rs
src/portgraph/iter.rs
src/unmanaged.rs
src/weights.rs

Adds a `PortOperation` to clarify when a port is removed vs when it's moved.
drive-by: add missing `ExactSizeIterator` to `Ports`

Pass the old link of a port when it is removed

---

src/portgraph.rs

Allows linking an incoming port to an outgoing port in `link_ports`. Before, this method restricted the first argument to be the outgoing port and the second argument to be the incoming one, but there is no real reason to require that (and allowing the reverse order simplifies some usecases).
I also added a `link_offsets` method that let's you connect pairs of `(NodeIndex, PortOffset)`. This is in addition to `link_nodes`, which takes `usize` offets for the ports. I'm leaving `link_nodes` as-is since it is quite convenient for testing and quickly defining graphs.

Allow reversed ports when linking

---

src/secondary.rs
src/unmanaged.rs

Extracted from #60. Partially implements #55.
The HashMap is a lot more tricky due to having to return references to a generic default value.

Implement SecondaryMap for HashSet

---

src/lib.rs

Direct serialization stores the underlying NonZeroU32 which can be confusing

serialize NodeIndex as 0-indexed

---

src/portgraph.rs

Prints
```
NodeIndex(0): Node {
inputs: [],
outputs: PortIndex(24)..PortIndex(42),
},
```
Instead of lists of sequential port indices when debugging nodes. This reduces some of the noise when printing big portgraphs.

Show ranges when debugging port indices

---

Cargo.toml
src/lib.rs
src/multiportgraph.rs
src/multiportgraph/iter.rs

Adds a wrapper for PortGraphs that allows multiple connections to the same port by creating implicit copy nodes.
Originally developed as part of [CQCL-DEV/hugr](https://github.com/CQCL-DEV/hugr/).

Add a MultiPortGraph wrapper

---

benches/benchmarks/generators.rs
benches/benchmarks/portgraph.rs
benches/benchmarks/substitute.rs
src/algorithms/dominators.rs
src/algorithms/post_order.rs
src/algorithms/toposort.rs
src/dot.rs
src/hierarchy.rs
src/lib.rs
src/multiportgraph.rs
src/multiportgraph/iter.rs
src/portgraph.rs
src/portgraph/iter.rs
src/proptest.rs
src/secondary.rs
src/substitute.rs
src/unmanaged.rs
src/view.rs
src/weights.rs

Splits the interfaces between
- `PortView`: Core node and port manipulation.
- `LinkView`: Adjacency-related methods. It defines a `LinkEndpoint` associated type so MultiPortGraph can use `SubPortIndex` instead of `PortIndex`.
- `MultiView`: Subports and methods specific to multiportgraphs.
The functionality should remain unchanged, but this will allow us to better generalize the interfaces (algorithms, dot, ...) in the future.
It would make sense to add a `WeighView` trait too, but we don't need it at the moment so I'll just leave the issue for the future.

Implement View traits for Portgraph and Multiportgraph

---

src/dot.rs

- Supports any `LinkView` graph, so MultiPortGraphs automatically hide the copy nodes.
- Refactors the combinatorial explosion of entry points (`dot_string`, `dot_string_with_hierarchy`, `dot_string_with_hierarchy_and_callbacks_and_...`) with a `DotFormatter` struct, so we can now do
```rust
graph.dot_format()
.with_hierarchy(&hier)
.with_node_style(|n| some_style(n))
.finish();
```
- Adds explicit `{Node,Port,Edge}Style` enums to better control the options
The formatting result is left unchanged. (Except for a small difference in the old `hier_graph_dot_string_with`, which didn't show the node ids)

Implement dot rendering on LinkView trait

---

Cargo.toml
src/view.rs
src/view/filter.rs
src/view/region.rs

- Adds a `NodeFiltered` adaptor that only expose some nodes of the graph.
- Uses that adaptor to define some `Region` and `FlatRegion` views focused on the children of a node in a hierarchy.
The code in `region.rs` is mostly delegating all work to the internal `NodeFiltered`, and copied once for each adaptor.

Graph filter adaptors

---

src/view/filter.rs
src/view/petgraph.rs

Uses hashsets for when `visit`ing the filtered adaptors to avoid overallocating memory

Implement petgraph traits for graph adaptors

---

Cargo.toml
RELEASES.md
src/view/region.rs

Drive-by: Clarify some docs in `region.rs`

Release 0.6.0

---

src/multiportgraph.rs
src/portgraph.rs
src/view.rs

This may be used to manipulate the order of nodes.
It required converting the free node linked list in `portgraph` into doubly-linked (so moved free entries can be updated).

Add a `PortMut::swap_nodes` method

---

src/hierarchy.rs

Reuses the code from `rekey`, but has some extra logic to handle cases where the two nodes are related.

Add a hierarchy::swap_nodes

---

src/dot.rs

This happened when using a filtered graph (e.g. FlatRegion).

fix: Ignore hierarchy elements that are not in the graph when displaying

---

src/view.rs
src/view/refs.rs

Add trait impls for refs

---

RELEASES.md

Not sure if this should be `0.8.0` instead, since the toposort update may break type inference, so it requires adding `: Toposort<_>` in some places.

Release v0.7.2

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/pr-title.yml
Cargo.toml
README.md

This should let us automate changelogs and releases in the future.

ci: Enforce conventional commit formatting

---

.github/workflows/ci.yml

#cisheddingfriday
- skips all non-required test jobs (the ones not for rust `stable`) when in the merge queue.
- Avoids compiling the tests twice on each job by tweaking the "Build with * features" step commands.
~The tests will fail until #106 is merged.~ (done)

ci: avoid running unnecessary jobs

---

Cargo.toml

BREAKING CHANGE: Updated the pyo3 dependency major version. All transitive dependencies to that crate must use the same version due to linking restrictions. See [links](https://doc.rust-lang.org/cargo/reference/resolver.html#links).

chore(deps)!: update pyo3 requirement from 0.19 to 0.20

---

benches/benchmarks/convex.rs
src/algorithms/convex.rs
src/view/subgraph.rs

ConvexChecker now uses the pre-computed node toposort to compute traverse the subgraph nodes and their causal future in order.
This should end up processing less nodes than the previous version, and let us avoid the temporary datastructure that required `&mut checker` all throughout the API.
I added some simple benchmarks, but unfortunately they are not the best at showing the improvements in this refactor (we end up traversing most of the nodes anyway).
In more real tests on `tket2` I saw small improvements, but nothing to write home about.

feat: Simpler convex checker, no longer requires `&mut`

---

.gitignore
DEVELOPMENT.md
justfile

drive-by: Copy justfile from hugr

docs: Coverage check section in DEVELOPMENT.md

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/proptest.rs

I've added a proptest generation for `MultiPortGraph`s.
I've also taken the opportunity to also rewrite and simplify the original generation for `PortGraph`s. This new version should be much better at shrinking.

feat: Proptest for Multiportgraph 

---

src/lib.rs
src/render.rs
src/render/dot.rs
src/render/mermaid.rs

Renames the `dot` module to `render`, and adds a mermaid formatter using the same style configuration structs.
BREAKING CHANGE: Moved `portgraph::dot` to `portgraph::render`

feat!: mermaid rendering

---

.github/pre-commit
justfile
src/multiportgraph.rs
src/multiportgraph/iter.rs
src/portgraph.rs
src/portgraph/iter.rs

The `all_links` iterator for both `Portgraph` and `Multiportgraph`, and `all_neighbours` for the latter yielded self-loops twice.
This in turn caused `insert_graph` to try inserting repeated links, as reported in #130. 
This PR fixes the error and adds tests for that.
Fixes #130.
drive-by: Add missing checks in the pre-commit hook.

fix: Link and neighbour iterators counting self-loops twice

---

src/lib.rs

I would find such a function a useful, straight-forward addition to the `PortOffset` API.

feat: Add PortOffset::opposite

---

Cargo.toml
src/algorithms.rs
src/algorithms/lca.rs

Implement the lowest-common-ancestor algorithm on hierarchies, using the "binary lifting" algorithm.
This is needed for the mermaid rendering, but it's also a useful algorithm to have around. (There's already been talk of using it in hugr).
Precomputation time: `O(n log d)`
`lca(a,b)` query time: `O(log d)`
`is_ancestor(a,b)` query time: `O(1)`
Memory: `O(n log d)`
where n=#nodes and d=max depth.
There's also a constant time algorithm based on RMQ, but it doesn't tend to be much faster than this one. This impl is much simpler.

feat: Efficient LCA algorithm for the hierarchy

---

benches/bench_main.rs
benches/benchmarks/mod.rs
benches/benchmarks/render.rs
src/render/mermaid.rs
src/snapshots/portgraph__render__test__flat__mermaid.snap
src/snapshots/portgraph__render__test__hierarchy__mermaid.snap
src/snapshots/portgraph__render__test__hierarchy_interregional__mermaid.snap
src/snapshots/portgraph__render__test__weighted__mermaid.snap

Defines intergraph edges on the parent region, so mermaid renders them correctly.
This required a lowest-common-ancestor implementation for the hierarchy. See #138.
I replaced the recursive DFS with a stack-based one that reuses the structures when exploring multiple trees.
I also added some benchmarks for both rendering algorithms.
This closes https://github.com/CQCL/hugr/issues/1197

fix: Intergraph edges in mermaid rendering

---

src/algorithms/convex.rs

feat: Fastpath for `is_node_convex` on a single node

---

Cargo.toml
benches/benchmarks/portgraph.rs
src/algorithms/post_order.rs
src/multiportgraph.rs
src/multiportgraph/iter.rs
src/portgraph.rs
src/portgraph/iter.rs
src/view.rs
src/view/filter.rs
src/view/petgraph.rs
src/view/refs.rs

Closes #119
This should simplify the implementation of #155, and any other new wrapper.
BREAKING CHANGE: Graph trait methods now return `impl Iterator`s instead of named associated types.

feat!: Use RPITIT for graph traits

---

src/view/filter.rs
src/view/subgraph.rs

Replaced the `Subgraph = FilteredGraph` alias with a concrete definition that avoids traversing the whole graph to filter nodes all the time.
Now `Subgraph::iter_nodes` is `O(nodes in subgraph)` instead of `O(n)`.
Closes #155.
BREAKING CHANGE: `Subgraph` is no longer an alias for `FilteredGraph`

perf!: Fix Subgraph O(n) complexity

---

src/hierarchy.rs
src/view.rs
src/view/flat_region.rs
src/view/region.rs

Followup to #157. Avoids using `FilteredGraph` for the implementation of `Region` and `FlatRegion` and instead implements the graph traits manually to avoid doing full-graph traversals when we can do better/faster checks.
Closes #159. Closes #145 (BFS rather than DFS). Closes #135.
BREAKING CHANGE:  `Region` and `FlatRegion` are no longer aliases of FilteredGraph

perf!: Manual impl of `Region`/`FlatRegion` for improved perf

---

src/render.rs
src/render/mermaid.rs
src/snapshots/portgraph__render__test__region_view__mermaid.snap

fix: Mermaid render of graph views was empty

---

src/hierarchy.rs

fix: Hierarchy descendants return root siblings

---

src/multiportgraph.rs

See test case. The problem is that iterating through the `dropped_ports` reads `self.multiport` using *old* indices, after `self.multiport` was mutated/renumbered by the callback earlier. (Thus, if the first OutPort was a multiport, removing the last InPort can end up reading a false positive.)
I've tried to see if I can break it by adding inports too, but in such cases all the ports get moved to a new "block" so there is no problem (hence, a more thorough "fix" to do *all reading* of self.multiport before *any writing* to it, including the reading+writing performed by `self.multiport.swap`, does not appear necessary).

fix: panic removing InPorts in MultiPortGraph::set_num_ports

---

src/render.rs
src/render/dot.rs
src/render/mermaid.rs
src/snapshots/portgraph__render__test__hierarchy__dot.snap
src/snapshots/portgraph__render__test__hierarchy__mermaid.snap

Lets us specify the node colour / stroke when rendering mermaid or dot graphs.

feat: Node style attributes in render options

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
benches/benchmarks/hierarchy.rs
benches/benchmarks/portgraph.rs
benches/benchmarks/toposort.rs
benches/helpers/traits.rs

Copied from hugr's CI.
Included the criterion bump from #225 as a test.
That PR tried to update the criterion dev-dependency to a version with MSRV 1.80, which caused a clippy error even though we don't need to build the benchmarks for MSRV.

ci: Test MSRV using minimal dependency versions

---

Cargo.lock
Cargo.toml
src/algorithms/convex.rs
src/algorithms/dynamic.rs
src/algorithms/toposort.rs
src/hierarchy.rs
src/index.rs
src/lib.rs
src/multiportgraph.rs
src/multiportgraph/iter.rs
src/portgraph.rs
src/portgraph/iter.rs
src/proptest.rs
src/render/mermaid.rs
src/unmanaged.rs
src/view.rs
src/view/filter.rs
src/view/flat_region.rs
src/view/refs.rs
src/view/region.rs
src/view/subgraph.rs
src/weights.rs

Closes #213
PortGraph and MultiPortGraph are now generic on `NodeIndex`, `PortIndex` and `PortOffset`. This allows the user to fix the size of these fields, using the unsigned integer of their choice.
To smooth the transition to fully generic indices, we currently only implement most features in this crate for `NodeIndex` and `PortIndex` fixed to `u32`. Generic `PortOffset` is supported in `PortView` and all related traits.
BREAKING CHANGE: `PortGraph` and `MultiPortGraph` now take generic type parameters. The default choices correspond to the old types. `PortView` has a new associated type `PortOffsetBase`.

feat!: Make PortGraph generic on node and port types

---

src/algorithms/dominators.rs
src/hierarchy.rs
src/index.rs
src/multiportgraph/iter.rs
src/portgraph.rs
src/portgraph/iter.rs

https://github.com/CQCL/portgraph/pull/230 results in a pretty significant performance hit. This PR attempts to fix that.
BREAKING CHANGE: `algorithms::dominators` returns a `Map` with values `MaybeNodeIndex` instead of `Option<NodeIndex>`. Convert to option using `to_option`.

refactor!: Add MaybeNodeIndex/PortIndex for performance

---

Cargo.lock
Cargo.toml
src/boundary.rs
src/index.rs
src/snapshots/portgraph__index__test_serde__serde_node_index.snap

https://github.com/CQCL/portgraph/pull/230 broke serialisation of `NodeIndex`, `PortIndex` and `PortOffset`. This PR restores the previous serialisation.
Should I mark this PR as breaking, even though it does not change any APIs? Sorry for the double breakage. The previous simpler serialisation was better, and this will also break less user code in the long run (minus the once that have already upgraded).
EDIT: We are yanking 0.15, restoring the old serialisation format is thus non-breaking.

fix: Serialise/Deserialise for indices is backwards compatible

---

Cargo.toml
benches/benchmarks/convex.rs
benches/helpers/generators.rs
src/algorithms.rs
src/algorithms/convex.rs
src/algorithms/convex/line_convex_checker.rs
src/algorithms/convex/topo_convex_checker.rs

This PR adds a new convex checker `LineConvexChecker`. All existing benchmarks `check_convexity_full`, `check_convexity_sparse` and `initialize_convexity` have been implemented for the new checker. I have also added a new `check_convexity_fixed_size` benchmark, which models more closely the kind of workloads that `tket2` uses these checkers for. The comparison between the two checkers is interesting
- 👍   on the `fixed_size` convexity check, the new checker is **~4x faster**, across all graph sizes. The one-time memory allocation would get amortised even further if more convexity checks were made in sequence (only making 3 in the benchmarks)
- 👍 on the `sparse` convexity check, the new checker is between **36% and 60% faster**
- on the `full` convexity check, the new checker is slightly …

feat: New ConvexChecker algorithm for Circuit-like graphs
